name: CI Build Setup
description: Sets up build dependencies

runs:
  using: composite
  steps:
    - id: python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - id: apt
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential
      shell: bash
    - id: arduino-cli
      run: |
        curl -fsSL \
        https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh
      shell: bash
    - id: clean-arduino-cache
      run: |
        rm -rf ~/.arduino15/packages/ ~/.arduino15/staging
      shell: bash
    - id: update-arduino-index
      run: |
        arduino-cli core update-index
      shell: bash
