; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = src/OTGW-firmware
data_dir = src/OTGW-firmware/data
default_envs = esp8266

[env]
framework = arduino
lib_extra_dirs = src/libraries
monitor_speed = 9600
board_build.filesystem = littlefs
extra_scripts = 
	pre:scripts/platformio_version.py
	pre:scripts/patch_pio_libs.py
lib_deps = 
	WiFiManager @ 2.0.17
	PubSubClient @ 2.8.0
	TelnetStream @ 1.3.0
	NetApiHelpers @ 1.0.2
	AceCommon @ 1.6.2
	AceSorting @ 1.0.0
	https://github.com/bxparks/AceTime.git#v2.0.1
	OneWire @ 2.3.8
	DallasTemperature @ 4.0.6
	WebSockets @ 2.3.6
	greiman/SSD1306Ascii @ 1.3.5
build_flags = 
	-DNO_GLOBAL_HTTPUPDATE

[env:esp8266]
platform = espressif8266@2.6.3
board = d1_mini
board_build.f_cpu = 160000000L
board_build.flash_mode = dio
board_build.ldscript = eagle.flash.4m2m.ld
build_flags = 
	${env.build_flags}
	-DBOARD_NODOSHOP_ESP8266
	-DAPI_WORD_LEN=32
	-DOpenThermResponseStatus=int
	-DOTDirectMode=int
	-DOTDirectRequestOrigin=int
	-Wno-unused-function
lib_ignore = OpenTherm Library
build_src_filter = +<*> -<OTDirect.ino>
upload_speed = 460800
platform_packages = platformio/tool-esptoolpy@^2.41100.0

[env:esp32]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.35/platform-espressif32.zip
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_size = 4MB
board_build.flash_mode = qio
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
platform_packages = platformio/tool-esptoolpy@^2.41100.0
build_flags = 
	${env.build_flags}
	-DBOARD_NODOSHOP_ESP32
	-DAPI_WORD_LEN=32
	-DOTGWFirmware=int
lib_deps = 
	${env.lib_deps}
	networking-for-arduino/EthernetESP32 @ 1.0.2
	h2zero/NimBLE-Arduino @ ^2.1.0
lib_ignore = OTGWSerial
upload_speed = 921600
board_build.partitions = partitions_otgw_esp32.csv
