#!/usr/bin/env python3
"""TASK-1185 AC#2 host harness: does a format-1 /ot-boiler.json, written by builds
that counted answers the gateway made itself as boiler evidence, stay out of RAM
and get replaced by format 2?

    python test/host/test_ot_support_migration.py                       # working tree only
    python test/host/test_ot_support_migration.py --old-rev de6b13ebe   # OLD vs FIX, with mutants

The six support bitmaps and the persistence functions (fileFindToken() through
saveOtSupportFilesIfDirty()) are sliced by anchor from OTGW-Core.ino and compiled
against an in-memory LittleFS. Each case dumps the bitmaps (R), the two file dirty
flags (D) and the /ot-boiler.json content (F). With --old-rev the run passes only
when FIX passes every case, OLD fails every defect case and differs from FIX in
exactly its listed parts, OLD passes every control case with exactly its listed
differences, and each mutant fails exactly its cases.
Exit code: 0 PASS, 1 FAIL, 2 harness error.
"""
import argparse
import re
import subprocess
import sys

from test_boiler_unsupported_origin import CORE, cut
from test_ot_reserved_range import GEN, HERE, find_vcvars
from test_pic_banner_dispatch import read

SLICES = [
    (CORE, r"^static uint8_t boilerLastMasterWasWrite\[32\]", r"^void clearBoilerUnsupportedDirty\(\)"),
    (CORE, r"^static bool fileFindToken\(File &f, const char \*target\)", r"^void saveOtSupportFilesIfDirty\(\)"),
]
DEFECT = {"M1": "RD", "M2": "RF", "M3": "R"}
CONTROL = {"C1": "F", "C2": "", "C3": "", "C4": ""}   # C1: this build writes format 2, the old one format 1
PARTS = ["R", "D", "F"]

MUTANTS = [
    ("MX1", "the load does not mark a migrated file for rewrite",
     [("boilerFileDirty     = boilerMigrated;", "boilerFileDirty     = false;")], ["M1", "M2"]),
    ("MX2", "the writer still writes format 1",
     [(r'{\"v\":2,\"device\":\"boiler\"', r'{\"v\":1,\"device\":\"boiler\"')], ["C1", "M2"]),
    ("MX3", "a format-1 boiler file loads again",
     [(r'if (strstr_P(header, PSTR("\"v\":2")) != nullptr) {',
       r'if (strstr_P(header, PSTR("\"v\":2")) != nullptr || strstr_P(header, PSTR("\"v\":1")) != nullptr) {')],
     ["M1", "M2"]),
]


def export(rev, out_dir):
    out_dir.mkdir(parents=True, exist_ok=True)
    origin = f"git {rev}" if rev else "working tree"
    lines = read(CORE, rev).splitlines()
    parts = [f"// GENERATED by test_ot_support_migration.py from the {origin}. Do not edit."]
    for path, start_rx, end_rx in SLICES:
        text, first, last = cut(lines, start_rx, end_rx)
        parts.append(f"// ---- {path}:{first}-{last} ----\n{text}")
    (out_dir / "core.inc").write_text("\n".join(parts) + "\n", encoding="utf-8")


def build_and_run(label, out_dir):
    exe = out_dir / "test_ot_support_migration.exe"
    if exe.exists():
        exe.unlink()
    bat = out_dir / "_compile.bat"
    fwd = str(out_dir).replace("\\", "/")
    bat.write_text("@echo off\r\n"
                   f"call \"{find_vcvars()}\" >nul 2>nul\r\n"
                   f"cl /nologo /EHsc /W3 /std:c++17 /Od /utf-8 /D_CRT_SECURE_NO_WARNINGS "
                   f"/Fo:\"{fwd}/\" /Fe:\"{exe}\" \"{HERE / 'test_ot_support_migration.cpp'}\" "
                   f"/I\"{out_dir}\"\r\n", encoding="ascii")
    c = subprocess.run(["cmd.exe", "/c", str(bat)], capture_output=True, text=True, errors="replace")
    if c.returncode != 0 or not exe.exists():
        print(c.stdout[-4000:], c.stderr[-2000:])
        print(f"COMPILATION FAILED ({label})")
        sys.exit(2)
    r = subprocess.run([str(exe), str(out_dir)], capture_output=True, text=True)
    cases = dict(re.findall(r"^CASE (\S+) (pass|FAIL)\b", r.stdout, re.M))
    dump = {}
    dump_file = out_dir / "cases.txt"
    if dump_file.exists():
        for line in dump_file.read_text(encoding="utf-8").splitlines():
            m = re.match(r"^(\S+) R=(\S+) D=(\S+) F=(\S+)$", line)
            if m:
                dump[m.group(1)] = dict(zip(PARTS, m.groups()[1:]))
    return r.returncode, cases, dump, r.stdout


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--old-rev", help="also build OLD from this git revision, compare, and run the mutants")
    args = ap.parse_args()

    fix_dir = GEN / "ot_support_migration" / "fix"
    export(None, fix_dir)
    fix_rc, fix_cases, fix_dump, out = build_and_run("FIX (working tree)", fix_dir)
    print("== FIX (working tree) ==")
    print(out, end="")
    fix_ok = (fix_rc == 0 and sorted(fix_cases) == sorted(list(DEFECT) + list(CONTROL))
              and all(v == "pass" for v in fix_cases.values()))
    checks = [("FIX passes every case, case list exact", fix_ok)]
    if not args.old_rev:
        print("RESULT:", "PASS" if fix_ok else "FAIL")
        return 0 if fix_ok else 1

    old_dir = GEN / "ot_support_migration" / "old"
    export(args.old_rev, old_dir)
    old_rc, old_cases, old_dump, out = build_and_run(f"OLD (git {args.old_rev})", old_dir)
    print(f"== OLD (git {args.old_rev}) ==")
    print(out, end="")

    def diff(case):
        o, f = old_dump.get(case), fix_dump.get(case)
        return None if o is None or f is None else "".join(p for p in PARTS if o[p] != f[p])

    bad_defect = [f"{c}({diff(c)})" for c, parts in DEFECT.items()
                  if not (old_cases.get(c) == "FAIL" and diff(c) == parts)]
    bad_control = [f"{c}({diff(c)})" for c, parts in CONTROL.items()
                   if not (old_cases.get(c) == "pass" and diff(c) == parts)]
    checks += [
        ("OLD exits 1", old_rc == 1),
        (f"defect cases fail on OLD and differ from FIX in exactly their parts (not matching: "
         f"{', '.join(bad_defect) or 'none'})", not bad_defect),
        (f"control cases pass on OLD and differ from FIX in exactly their listed parts (not matching: "
         f"{', '.join(bad_control) or 'none'})", not bad_control),
    ]
    for mid, what, reps, want_fail in MUTANTS:
        d = GEN / "ot_support_migration" / mid
        export(None, d)
        text = (d / "core.inc").read_text(encoding="utf-8")
        for a, b in reps:
            if text.count(a) != 1:
                print(f"MUTANT {mid}: pattern must match exactly once, got {text.count(a)}: {a}")
                return 2
            text = text.replace(a, b)
        (d / "core.inc").write_text(text, encoding="utf-8")
        _, cases, _, _ = build_and_run(f"mutant {mid}", d)
        failed = sorted(c for c, v in cases.items() if v == "FAIL")
        print(f"== {mid}: {what} -> failed cases: {', '.join(failed) or 'none'}")
        checks.append((f"{mid} ({what}) fails exactly {','.join(want_fail)}", failed == sorted(want_fail)))

    print("== old-vs-fix verdict ==")
    for text, ok in checks:
        print(f"  {text}: {'yes' if ok else 'NO'}")
    ok = all(ok for _, ok in checks)
    print("RESULT:", "PASS" if ok else "FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
