#!/usr/bin/env python3
"""TASK-1133 AC#1 host harness: does POST /api/v2/otgw/diagnose answer 4xx and
write nothing to the PIC when the body lacks a usable "data" field?

    python test/host/test_diagnose_handler.py                  # working tree only
    python test/host/test_diagnose_handler.py --old-rev 88f245717^

Compiles the REAL diagnose branch of the /api/v2/otgw handler (restAPI.ino,
the lines between its 'diagnose' test and the next branch) inside a harness
function, together with the REAL JSON scanner (jsonStuff.ino, between the
'host-testable JSON scanner' sentinels). The PIC transmit queue, the HTTP
responses and the body accessor are doubles that record what the branch did.
With --old-rev, both slices come from that revision instead.
The run passes only when FIX passes every case and OLD fails exactly the
defect cases (H1, H3, H4, H7) while passing the controls (H2, H5, H6).
Exit code: 0 PASS, 1 FAIL, 2 harness error.
"""
import argparse
import re
import subprocess
import sys

from test_ot_reserved_range import GEN, HERE, REPO, find_vcvars

REST = "src/OTGW-firmware/restAPI.ino"
JSON = "src/OTGW-firmware/jsonStuff.ino"
DEFECT = ["H1", "H3", "H4", "H7"]
CONTROL = ["H2", "H5", "H6"]


def read(path, rev):
    if rev is None:
        return (REPO / path).read_text(encoding="utf-8", errors="replace")
    return subprocess.run(["git", "-C", str(REPO), "show", f"{rev}:{path}"], capture_output=True,
                          text=True, encoding="utf-8", errors="replace", check=True).stdout


def one_line(lines, rx, after=0):
    hits = [i for i in range(after, len(lines)) if re.search(rx, lines[i])]
    if not hits:
        raise SystemExit(f"anchor not found: {rx}")
    return hits[0]


def slice_branch_body(lines):
    """The body of the 'diagnose' branch: the lines after its test, up to the next branch."""
    start = one_line(lines, r'strcmp_P\(words\[4\], PSTR\("diagnose"\)\) == 0\) \{\s*$')
    if len([l for l in lines if re.search(r'strcmp_P\(words\[4\], PSTR\("diagnose"\)\) == 0\) \{\s*$', l)]) != 1:
        raise SystemExit("the diagnose branch anchor must match exactly once")
    end = one_line(lines, r'^\s*\} else if \(strcmp_P\(words\[4\], PSTR\("discovery"\)\)', start + 1)
    return "\n".join(lines[start + 1:end])


def slice_scanner(lines):
    begin = one_line(lines, r"host-testable JSON scanner: BEGIN")
    end = one_line(lines, r"host-testable JSON scanner: END", begin + 1)
    return "\n".join(lines[begin:end + 1])


def export(rev, out_dir):
    out_dir.mkdir(parents=True, exist_ok=True)
    origin = f"git {rev}" if rev else "working tree"
    head = f"// GENERATED by test_diagnose_handler.py from {origin}. Do not edit.\n"
    (out_dir / "diagnose_scanner.inc").write_text(head + slice_scanner(read(JSON, rev).splitlines()) + "\n",
                                                  encoding="utf-8")
    (out_dir / "diagnose_branch.inc").write_text(head + slice_branch_body(read(REST, rev).splitlines()) + "\n",
                                                 encoding="utf-8")


def build_and_run(label, out_dir):
    exe = out_dir / "test_diagnose_handler.exe"
    if exe.exists():
        exe.unlink()
    bat = out_dir / "_compile.bat"
    fwd = str(out_dir).replace("\\", "/")
    bat.write_text("@echo off\r\n"
                   f"call \"{find_vcvars()}\" >nul 2>nul\r\n"
                   f"cl /nologo /EHsc /W3 /std:c++17 /utf-8 /D_CRT_SECURE_NO_WARNINGS "
                   f"/Fo:\"{fwd}/\" /Fe:\"{exe}\" \"{HERE / 'test_diagnose_handler.cpp'}\" /I\"{out_dir}\" /I\"{HERE}\"\r\n",
                   encoding="ascii")
    c = subprocess.run(["cmd.exe", "/c", str(bat)], capture_output=True, text=True, errors="replace")
    if c.returncode != 0 or not exe.exists():
        print(c.stdout[-3000:], c.stderr[-2000:])
        print(f"COMPILATION FAILED ({label})")
        sys.exit(2)
    r = subprocess.run([str(exe)], capture_output=True, text=True)
    print(f"== {label} ==")
    print(r.stdout, end="")
    return r.returncode, dict(re.findall(r"^CASE (\S+) (pass|FAIL)\b", r.stdout, re.M))


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--old-rev", help="also build OLD from this git revision and compare")
    args = ap.parse_args()
    fix_dir = GEN / "diagnose_handler" / "fix"
    export(None, fix_dir)
    fix_rc, fix_cases = build_and_run("FIX (working tree)", fix_dir)
    if not args.old_rev:
        print("RESULT:", "PASS" if fix_rc == 0 else "FAIL")
        return 0 if fix_rc == 0 else 1
    old_dir = GEN / "diagnose_handler" / "old"
    export(args.old_rev, old_dir)
    old_rc, old_cases = build_and_run(f"OLD (git {args.old_rev})", old_dir)
    checks = [
        ("FIX passes every case", fix_rc == 0 and sorted(fix_cases) == sorted(DEFECT + CONTROL)
         and all(v == "pass" for v in fix_cases.values())),
        ("OLD fails exactly the defect cases " + ",".join(DEFECT), all(old_cases.get(c) == "FAIL" for c in DEFECT)),
        ("OLD passes the controls " + ",".join(CONTROL), all(old_cases.get(c) == "pass" for c in CONTROL)),
        ("OLD exits 1", old_rc == 1),
    ]
    print("== old-vs-fix verdict ==")
    for text, ok in checks:
        print(f"  {text}: {'yes' if ok else 'NO'}")
    ok = all(ok for _, ok in checks)
    print("RESULT:", "PASS" if ok else "FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
