#!/usr/bin/env python3
"""TASK-1111 AC#1 host harness: does every byte the PIC task reads reach
OTGWstream (port 25238) verbatim, without waiting for a line terminator?

    python test/host/test_raw_passthrough.py                      # working tree only
    python test/host/test_raw_passthrough.py --old-rev c1012f265^

Compiles the REAL byte path from OTGW-Core.ino, sliced by anchor: the PIC
task's picSerialDrainOnce() with enqueueOTFrame(), and the loop side's
drainOTFrameQueue() (and, where the revision has them, picSerialFlushRawChunk()
and drainOTRawQueue()), plus the message types from OTGW-Core.h. The UART,
the value queues, the clock and OTGWstream are doubles. The driver feeds bytes
at 9600 baud (one per ms), ticks the task every 2 ms as the firmware does, runs
the loop drain after each tick, and compares what OTGWstream received with
what the PIC sent.

With --old-rev, all slices come from that revision (before TASK-1111 it had no
raw queue; 25238 was fed by whole lines in drainOTFrameQueue()).
The run passes only when FIX passes every case and OLD fails exactly the defect
cases (P2, P3, P4, P5) while passing the controls (P1, P6).
Exit code: 0 PASS, 1 FAIL, 2 harness error.
"""
import argparse
import re
import subprocess
import sys

from test_ot_reserved_range import GEN, HERE, REPO, find_vcvars, slice_by_anchor

HDR = "src/OTGW-firmware/OTGW-Core.h"
CORE = "src/OTGW-firmware/OTGW-Core.ino"
DEFECT = ["P2", "P3", "P4", "P5"]
CONTROL = ["P1", "P6"]


def read(path, rev):
    if rev is None:
        return (REPO / path).read_text(encoding="utf-8", errors="replace")
    return subprocess.run(["git", "-C", str(REPO), "show", f"{rev}:{path}"], capture_output=True,
                          text=True, encoding="utf-8", errors="replace", check=True).stdout


def find_once(lines, rx, required=True):
    hits = [i for i, l in enumerate(lines) if re.search(rx, l)]
    if len(hits) > 1:
        raise SystemExit(f"anchor matches {len(hits)} lines: {rx}")
    if not hits:
        if required:
            raise SystemExit(f"anchor not found: {rx}")
        return None
    return hits[0]


def line(lines, rx, required=True):
    i = find_once(lines, rx, required)
    return None if i is None else lines[i]


def construct(lines, rx, required=True):
    if find_once(lines, rx, required) is None:
        return None
    return slice_by_anchor(lines, rx)


def until(lines, start_rx, stop_rx):
    """From the start line up to (not including) the first line matching stop_rx."""
    start = find_once(lines, start_rx)
    stop = next((i for i in range(start + 1, len(lines)) if re.search(stop_rx, lines[i])), None)
    if stop is None:
        raise SystemExit(f"no stop line after {start_rx}")
    return "\n".join(lines[start:stop])


def export(rev, out_dir):
    out_dir.mkdir(parents=True, exist_ok=True)
    h = read(HDR, rev).splitlines()
    c = read(CORE, rev).splitlines()
    raw = find_once(h, r"^#define OT_RAW_CHUNK_MAX\b", required=False) is not None
    parts = [
        line(h, r"^#define MAX_BUFFER_READ\b"),
        line(h, r"^#define MAX_BUFFER_WRITE\b"),
        construct(h, r"^enum OTFrameSource\b"),
        construct(h, r"^struct OTFrameMsg \{"),
        line(h, r"^#define OT_TX_CHUNK_MAX\b"),
        construct(h, r"^struct OTTxMsg \{"),
    ]
    if raw:
        parts += [
            "#define HARNESS_HAS_RAW_PATH 1",
            line(h, r"^#define OT_RAW_CHUNK_MAX\b"),
            construct(h, r"^struct OTRawMsg \{"),
            line(h, r"^#define OT_RAW_QUEUE_DEPTH\b"),
            line(h, r"^#define OT_RAW_COALESCE_MS\b"),
        ]
    parts += [
        line(c, r"^PlatformQueue otFrameQueue\b"),
        line(c, r"^static uint32_t otFrameQueueDrops\b"),
        line(c, r"^PlatformQueue otTxQueue\b"),
    ]
    if raw:
        parts.append(line(c, r"^PlatformQueue otRawQueue\b"))
    parts += [
        until(c, r"^static volatile bool\s+g_picRxOverrunPending\b", r"^#endif"),
        construct(c, r"^bool enqueueOTFrame\("),
    ]
    if raw:
        parts.append(construct(c, r"^void drainOTRawQueue\(\)"))
    parts.append(construct(c, r"^void drainOTFrameQueue\(\)"))
    if raw:
        parts.append(construct(c, r"^static void picSerialFlushRawChunk\("))
    parts.append(construct(c, r"^void picSerialDrainOnce\(\)"))
    origin = f"git {rev}" if rev else "working tree"
    text = f"// GENERATED by test_raw_passthrough.py from {origin}. Do not edit.\n" + "\n\n".join(parts) + "\n"
    (out_dir / "raw_passthrough.inc").write_text(text, encoding="utf-8")
    return raw


def build_and_run(label, out_dir):
    exe = out_dir / "test_raw_passthrough.exe"
    if exe.exists():
        exe.unlink()
    bat = out_dir / "_compile.bat"
    fwd = str(out_dir).replace("\\", "/")
    bat.write_text("@echo off\r\n"
                   f"call \"{find_vcvars()}\" >nul 2>nul\r\n"
                   f"cl /nologo /EHsc /W3 /std:c++17 /utf-8 /D_CRT_SECURE_NO_WARNINGS "
                   f"/Fo:\"{fwd}/\" /Fe:\"{exe}\" \"{HERE / 'test_raw_passthrough.cpp'}\" /I\"{out_dir}\" /I\"{HERE}\"\r\n",
                   encoding="ascii")
    c = subprocess.run(["cmd.exe", "/c", str(bat)], capture_output=True, text=True, errors="replace")
    if c.returncode != 0 or not exe.exists():
        print(c.stdout[-3000:], c.stderr[-2000:])
        print(f"COMPILATION FAILED ({label})")
        sys.exit(2)
    r = subprocess.run([str(exe)], capture_output=True, text=True, errors="replace")
    print(f"== {label} ==")
    print(r.stdout, end="")
    return r.returncode, dict(re.findall(r"^CASE (\S+) (pass|FAIL)\b", r.stdout, re.M))


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--old-rev", help="also build OLD from this git revision and compare")
    args = ap.parse_args()
    fix_dir = GEN / "raw_passthrough" / "fix"
    if not export(None, fix_dir):
        raise SystemExit("the working tree has no raw passthrough path (OT_RAW_CHUNK_MAX missing)")
    fix_rc, fix_cases = build_and_run("FIX (working tree)", fix_dir)
    if not args.old_rev:
        print("RESULT:", "PASS" if fix_rc == 0 else "FAIL")
        return 0 if fix_rc == 0 else 1
    old_dir = GEN / "raw_passthrough" / "old"
    export(args.old_rev, old_dir)
    old_rc, old_cases = build_and_run(f"OLD (git {args.old_rev})", old_dir)
    checks = [
        ("FIX passes every case", fix_rc == 0 and sorted(fix_cases) == sorted(DEFECT + CONTROL)
         and all(v == "pass" for v in fix_cases.values())),
        ("OLD fails exactly the defect cases " + ",".join(DEFECT), all(old_cases.get(c) == "FAIL" for c in DEFECT)),
        ("OLD passes the controls " + ",".join(CONTROL), all(old_cases.get(c) == "pass" for c in CONTROL)),
        ("OLD exits 1", old_rc == 1),
    ]
    print("== old-vs-fix verdict ==")
    for text, ok in checks:
        print(f"  {text}: {'yes' if ok else 'NO'}")
    ok = all(ok for _, ok in checks)
    print("RESULT:", "PASS" if ok else "FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
